title: Jake Lahoff # your name (or website title) here
logo: "/images/IMG_33742.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Portfolio for GES 486 at UMBC 
  <br><br>
  Projects will be added to this portfolio as they are completed 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
