title: Jake Lahoff # your name (or website title) here
logo: "/images/me.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Undergraduate student at UMBC, majoring in Geography and Environmental Science with a certificate is Geographic Information Systems
  <br><br>
  This serves as a portfolio for GES 486, Advanced GIS, at UMBC
  <br><br>
  <a href="https://www.linkedin.com/in/jake-l-4956831a4/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
