title: Jake Lahoff # your name (or website title) here
logo: "/images/me.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br> 
  Located in Baltimore, Maryland
  <br><br>
  BS in Environmental Science and Geography from UMBC
  <br><br>
  Geographic Information Science certificate from UMBC
  <br><br>
  Baltimore County Department of Public Works and Transportation GIS intern
  
  <a href="https://www.linkedin.com/in/jake-l-4956831a4/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
